--- #YAML:1.0
name:                Geo-Point
version:             0.06
abstract:            Geographical structures
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Geo::Distance:                 0.06
    Geo::Proj4:                    0.96
    Math::Polygon:                 0.003
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mark Overmeer
